### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by irgendwr** [wtolson/go-taglib#13]
Hi, thanks for writing this wrapper!
I noticed that this repo is missing a license. It would be great if you could [choose](https://choosealicense.com/) and add a proper license like the [MIT License](https://choosealicense.com/licenses/mit/), [Unlicense](https://choosealicense.com/licenses/unlicense/) or a [Creative Commons License](https://creativecommons.org/share-your-work/) for example.

The reason for this is that
1. https://pkg.go.dev/github.com/wtolson/go-taglib requires a license to render the documentation
2. It's impossible to be "legally safe" as a user otherwise

**Comment by wtolson** [comment]
Wow, can't believe I never stuck a license on this. Thanks.
