### ISSUE TITLE
go-taglib import problem

### ISSUE THREAD

**Issue by charlesvdv** [wtolson/go-taglib#4]
Hi !

I have a little problem with your library. As I import your project with : "github.com/wtolson/go-taglib", I have to call the library function with go-taglib.SomeFunction(...) but the - is not recognise for the package name. Could you (if it does not bother you of course), change the name of the repository otherwise every people using the library will have to change the folder name ? 

Thanks a lot !

**Comment by wtolson** [comment]
Hi, the import path is "github.com/wtolson/go-taglib" however the package name is just "taglib". For example:

    package main

    import (
    	"fmt"
    	"github.com/wtolson/go-taglib"
    )

    func main() {
    	file, _ := taglib.Read("test.mp3")
    	fmt.Println(file.Title())
    }

Hope that helps.

**Comment by charlesvdv** [comment]
Ho sorry I didn't know that. 
Thanks a lot for the helps !
